### ISSUE TITLE
Bug in fine-tuning

### ISSUE THREAD

**Issue by amirmfarzane** [facebookresearch/seamless_communication#472]
I tried different ways to fine-tune seamless but it needs more than capacity of my gpus.
And i got cuda out of memory error.
Please help me.

**Comment by amirmfarzane** [comment]
How handle diffrent parallel parts

**Comment by developeranalyser** [comment]
optimize memory  leaks in code

**Comment by amirmfarzane** [comment]
Can you say specifically which part  of code ??!!
Finetune file make a lot of processes and each one get a part of GPU.
How decrease these file?
How reduce memory leak generally?

**Comment by developeranalyser** [comment]
من این کار را انجام دادم و مصرف حافظه کمتر از 18 گیگ شد 
به اینجا مراجعه کنید و بسیاری از توسعه ها و بهینه سازی ها

https://github.com/developeranalyser/my_seamless_communication


اما یک مشکل بزرگتر وجود دارد 
مدل آموزش نمی بیند و اصلاح نمی کند 
به هر حال  شما بررسی کنید و به من اطلاع بدهید 
بیش از 3ماه زمان صرف کردم و خسته شدم .............
به امید خدا

**Comment by amirmfarzane** [comment]
Thanks, i did fine-tuning.
After fine-tuning, how use new check points for my model?
Because loss decreased significantly and now i want to get WER on new test data.

**Comment by developeranalyser** [comment]
شما برای چه زبانی این کار را انجام دادید ؟
دیتاست خودتان را می توانید به من بدهید ؟
من هم تنظیم دقیق انجام می دهم و زیان کاهش می یابد اما بر اساس داده های جدید که آموزش دیده است خروجی مدل اصلاح نمی شود و مثل قبل اشتباه می خواند.........


تقدیم به شما  : )


%cd /content/my_seamless_communication/src
import torch


from my_seamless_communication.src.seamless_communication.models.unity import (
    UnitYModel,
    UnitYT2UModel,
)
from my_seamless_communication.src.seamless_communication.inference.translator import Translator



from fairseq2.typing import DataType, Device
device = Device("cuda:0")
def get_default_dtype() -> DataType:
    if device == Device("cpu"):
        dtype = torch.float32
    else:
        dtype = torch.float16
    return dtype


# translator = Translator('seamlessM4T_v2_large', "vocoder_v2", device, dtype= get_default_dtype())
# translator = Translator('seamlessM4T_large', "vocoder_36langs", device, dtype= get_default_dtype())
translator = Translator('seamlessM4T_large', "vocoder_36langs", device, dtype= get_default_dtype())
# translator = Translator('seamlessM4T_medium', "vocoder_v2", device, dtype= get_default_dtype())



my_trained=torch.load('/content/_my_trained.pth',map_location=torch.device('cuda:0'))
res={}
for e,w in  my_trained.items():
    res.update({e[6:]:w})
finall={}
finall.update({'model':res})
# res={'model':res['']}
print(finall)


translator.model.load_state_dict(finall['model'])

**Comment by developeranalyser** [comment]
... and you can use evaluate.py

**Comment by amirmfarzane** [comment]
Thanks
I'm not sure that model results improved or not
i'm only speaking based on loss of validation.
My dataset is persian.
And how use checkpoints as new model for fine-tuning??!!

I used 
my_trained=torch.load('/content/_my_trained.pth',map_location=torch.device('cuda:0'))
res={}
for e,w in my_trained.items():
res.update({e[6:]:w})
finall={}
finall.update({'model':res})
-# res={'model':res['']}
for loader file but didn't work!

**Comment by amirmfarzane** [comment]
Also i couldn't use this 
my_trained=torch.load('/content/_my_trained.pth',map_location=torch.device('cuda:0'))
res={}
for e,w in my_trained.items():
res.update({e[6:]:w})
finall={}
finall.update({'model':res})
-# res={'model':res['']}
to load checkpoints

**Comment by developeranalyser** [comment]
خب چی شد ؟ چه خطایی داشتید ؟

**Comment by amirmfarzane** [comment]
> خب چی شد ؟ چه خطایی داشتید ؟
> Missing key(s) in state_dict
Checkpoints are not similar to real checkpoints of seamless.
A lot of missing keys.

**Comment by amirmfarzane** [comment]
- Missing key(s) in state_dict
Checkpoints are not similar to real checkpoints of seamless.
A lot of missing keys.

**Comment by developeranalyser** [comment]
train model must be v1 and translator must be v1    its ok ?

**Comment by developeranalyser** [comment]
به نتیجه ای رسیدید ؟

**Comment by amirmfarzane** [comment]
> train model must be v1 and translator must be v1 its ok ?

Both are seamlessM4T_medium.

**Comment by developeranalyser** [comment]
خب ؟  به نتیجه ای نرسیدید

**Comment by amirmfarzane** [comment]
No.
When i use m4t_evaluate  to use checkpoints
I get
'''
RuntimeError: Error(s) in loading state_dict for Wav2Vec2Frontend:
        Missing key(s) in state_dict: "post_extract_layer_norm.weight", "post_extract_layer_norm.bias", "model_dim_proj.weight", "model_dim_proj.bias". 
'''

**Comment by amirmfarzane** [comment]
See here https://github.com/facebookresearch/seamless_communication/discussions/459.

I changed the `load_checkpoints` function, and the previous error was corrected.
I didn't use `load_checkpoints` in evaluate.py.
Also WER decreased on my test data set, and the new checkpoints were impactful.

**Comment by developeranalyser** [comment]
this model is not good and made me miserable
better go for a better way
It is good to cooperate because we have the same goal

**Comment by RRThivyan** [comment]
Hi, can anyone help me? I am finetuning the v2_large model for tts as some languages are not speech supported. my model is not loaded due to final_proj.weights missing. I even tried the steps showed in finetuning for korean, but still getting the same error. How can we use our finetune .pt model for our purpose?

**Comment by SoheilDE** [comment]
It seems that in the fine-tuned model, only the weights related to the specific task are saved, so we cannot use the fine-tuned model directly for deployment. You need to replace the weights from the fine-tuned model into the main model to deploy it on your service.

**Comment by johneortega** [comment]
Okay, this is exactly what several people have reported but it does not seem to really have been fixed. How do we update all the weights on the main model after creating a fine-tuned model. I fine-tuned the v2-large model and ran the eval cli script with the --load-checkpoint pointing the fine-tuned checkpoint, I got this error:

RuntimeError: Error(s) in loading state_dict for Wav2Vec2Frontend:
        Missing key(s) in state_dict: "post_extract_layer_norm.weight", "post_extract_layer_norm.bias", "model_dim_proj.weight", "model_dim_proj.bias"

It might be solved in some issue but the code is not given really that fixes it.
